fix firefox mouseup event not working properly.
The error is: TypeError: t.getAttribute is not a function

In firefox, when you mousedown, then hold it and release mouseup outside of the browser frame,
firefox reports event.target === HTMLDocument which has no getAttribute function.

The fix just adds an extra check to make sure event.target has a nodeType of 1 (Element), which is what we want.