Change markdown processor to kramdown.
Running 'grunt' in the terminal gives this error:

    Markdown processor: "redcarpet" is not a valid Markdown processor.
        Available processors are: kramdown
    Conversion error: Jekyll::Converters::Markdown encountered an error while converting 'documentation/api.md':
        Invalid Markdown processor given: redcarpet
        ERROR: YOUR SITE COULD NOT BE BUILT:

Doing 'gem list' shows that redcarpet is not installed and though this could probably made to work if it is separately installed, it seems easier to change the markdown processor to kramdown which is the default.