Update gruntfile.js and packages.json because of changes to grunt-sass.
When attempting to run grunt after installation according to the instructions, the terminal shows:
    Running "sass:dist" (sass) task
    Fatal error: The implementation option must be passed to the Sass task
That led me to https://github.com/them-es/themes-starter-bootstrap/issues/1 and then https://www.npmjs.com/package/grunt-sass/v/3.0.0

Adding just the options block in the gruntfile but failing to update packages leads to this error in the terminal:
    Loading "Gruntfile.js" tasks...ERROR
    >> Error: Cannot find module 'node-sass'
so I first added
   "node-sass": "*"
but after running
    npm install --save-dev node-sass grunt-sass
the line was changed to
    "node-sass": "^4.13.1"

Initially I had an error related to the jekyllConfig section of gruntfile.js indicating that redcarpet was not installed so I changed line 24 to
    "markdown: kramdown \r\n"+
but now it seems to work just fine with the original setting.